edition = "2021"
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
max_width = 80

unstable_features = true
comment_width = 80
wrap_comments = true
normalize_comments = true
